# Generated by Django 4.0.2 on 2022-02-10 11:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_purchase_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchased_items',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchased_items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 14, 22, 56, 964058)),
        ),
    ]
