# Generated by Django 4.0.2 on 2022-02-10 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_purchase_purchased_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchased_items',
            new_name='purchased_item',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 14, 25, 48, 196532)),
        ),
    ]
