# Generated by Django 4.0.2 on 2022-02-10 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_rename_purchased_items_purchase_purchased_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 17, 46, 36, 573263)),
        ),
    ]
