# Generated by Django 4.0.2 on 2022-02-10 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_purchase_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=datetime.date(2022, 2, 11)),
        ),
        migrations.AddField(
            model_name='purchase',
            name='time',
            field=models.TimeField(default=datetime.time(0, 29, 30, 906346)),
        ),
    ]
