# Generated by Django 4.0.2 on 2022-02-10 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_purchase_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='time',
        ),
        migrations.AddField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 0, 51, 14, 482281)),
        ),
    ]
